# Generated by Django 5.0.6 on 2024-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='expenses_monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='income_monthly',
            field=models.IntegerField(default=0),
        ),
    ]
